FORMAT: 1A

# Banana-Fish
**BananaFish** is an API that allows people to find games, companies, and jobs in the gaming industry.





# Group Game
API calls related to resources of the **Games API**

## Games [/models/Game.py/{game_id}]
Attributes belonging to a **game**
+ Game ID
+ Name
+ Image
+ Original Release Date
+ Deck
+ Description
+ Company ID

+ Parameters
    + game_id (required, number, `1`) ... ID of the Game in form of an integer
    
### Lookup a Game [GET]
+ Response 200 (application/json)

        {
            "game_id": 1,
            "name": "League of Legends",
            "image": "image.jpg",
            "original_release_date": "10-27-2009",
            "deck": "MOBA",
            "description": "League of Legends is a fast-paced, competitive online game that blends the speed and intensity of an RTS with RPG elements",
            "company_id": 1
        }

### Add a Game [POST]
+ Request (application/json)

        {
            "name": "World of Warcraft",
            "original_release_date": "11-23-2004",
            "deck": "MMORPG",
            "description": "a massively multiplayer online role-playing game (MMORPG) created in 2004 by Blizzard Entertainment",
            "company_id": 2
        }

+ Response 201 (application/json)

    + Header
    
            Location: /models/Game.py/2
    
    + Body
    
            {
                "game_id": 2,
                "name": "World of Warcraft",
                "image": "image.jpg",
                "original_release_date": "11-23-2004",
                "deck": "MMORPG",
                "description": "a massively multiplayer online role-playing game (MMORPG) created in 2004 by Blizzard Entertainment",
                "company_id": 2
            }
            
#Get all Games [/models/Game.py]

###Get a list of all Games [GET]
+ Response 200  (application/json)

        {
            "game1":
            {
                "game_id": 1,
                "name": "League of Legends",
                "image": "image.jpg",
                "original_release_date": "10-27-2009",
                "deck": "MOBA",
                "description": "League of Legends is a fast-paced, competitive online game that blends the speed and intensity of an RTS with RPG elements",
                "company_id": 1
            }, 
            "game2":
            {
                "game_id": 2,
                "name": "World of Warcraft",
                "image": "image.jpg",
                "original_release_date": "11-23-2004",
                "deck": "MMORPG",
                "description": "a massively multiplayer online role-playing game (MMORPG) created in 2004 by Blizzard Entertainment",
                "company_id": 2
            }
        }






# Group Company
User may search up companies of interest to look up basic information about them.
## Companies [/models/Company.py/{company_id}]
Attributes belonging to a **company**
+ Company ID
+ Name
+ Deck
+ Description
+ Image
+ Address
+ City
+ State
+ Country
+ Phone Number
+ Date Founded
+ Website

+ Parameters
    + company_id (required, number, `1`) ... ID of the Company in form of an integer
    
### Lookup a Company [GET]
+ Response 200 (application/json)

        {
            "company_id": 1,
            "name": Riot Games,
            "deck": Created LOL,
            "description": Creator of the popular MOBA League of Legends,
            "image": image.jpg,
            "address": 2450 Broadway, Santa Monica, CA 90404,
            "city": Santa Monica,
            "state": California,
            "country": USA, 
            "phone": ,
            "date_founded": 10-27-2009,
            "website": www.riotgames.com/
        }

### Add a Company [POST]
+ Request (application/json)

        {
            "company_id": 2,
            "name": Blizzard,
            "deck": Created WOW,
            "description": Creator of the popular MMO World of Warcraft,
            "image": image2.jpg,
            "address": 16215 Alton Pkwy,
            "city": Irving,
            "state": California,
            "country": USA, 
            "phone": ,
            "date_founded": 11-23-2004,
            "website": www.blizzard.com/
        }

+ Response 201 (application/json)

    + Header
    
            Location: /models/Company.py/2
    
    + Body
    
            {
                "company_id": 2,
                "name": Blizzard,
                "deck": Created WOW,
                "description": Creator of the popular MMO World of Warcraft,
                "image": image2.jpg,
                "address": 16215 Alton Pkwy,
                "city": Irving,
                "state": California,
                "country": USA, 
                "phone": ,
                "date_founded": 11-23-2004,
                "website": www.blizzard.com/
            }

#Get all Companies [/models/Company.py]

###Get a list of companies [GET]
+ Response 200 (application/json)

        {
            "company1": {
                "company_id": 1,
                "name": Riot Games,
                "deck": Created LOL,
                "description": Creator of the popular MOBA League of Legends,
                "image": image.jpg,
                "address": 2450 Broadway, Santa Monica, CA 90404,
                "city": Santa Monica,
                "state": California,
                "country": USA, 
                "phone": ,
                "date_founded": 10-27-2009,
                "website": www.riotgames.com/
            },
            "company2": {
                "company_id": 2,
                "name": Blizzard,
                "deck": Created WOW,
                "description": Creator of the popular MMO World of Warcraft,
                "image": image2.jpg,
                "address": 16215 Alton Pkwy,
                "city": Irving,
                "state": California,
                "country": USA, 
                "phone": ,
                "date_founded": 11-23-2004,
                "website": www.blizzard.com/
            }




# Group Job
In this section, if a user is interested with a *specific* company, they can
search up variety types of jobs/careers that companies are hiring.
## Job [/models/Job.py/{job_id}]
Attributes belonging to a **Job**:
+ Company ID
+ Company Name
+ Job ID
+ Job Position
+ Job Description
+ Job Expectations
+ Job Responsibilities
+ Job Location

+ Parameters
    + job_id (required, number, `1`) ... ID of the Job in form of an integer

### Lookup a Job [GET]
+ Response 200 (application/json)

        {
            "company_id": 1,
            "company_name": "Riot Games",
            "job_id": 1,
            "job_position": "Product Manager",
            "job_description": "As the Product Manager, you’ll lead a cross functional, massively collaborative team that focuses on more than exceptional origination through delivery of multiple products and initiatives. Flexibility is your middle name and you’re at ease handling anything from brainstorming ways to delight players at community events to the core building blocks of our organized play strategy. Owning products and leading teams, you’re an inspiring coach, naturally leveling up the people around you.
                                As a Dublin Rioter, you’ll join a smaller team of internationally and culturally diverse professionals that share our prioritization of player experience, rejection of convention and maniacal passion for gaming. With teams in Player Support, Community and Marketing, Riot Games Dublin is dedicated to creating unique player experiences that show local players they aren't lost in translation.",
            "job_expectations": "Educated and experienced, A visionary, A seasoned leader, Self-motivated, Empathetic, A player",
            "job_responsibilities": "Be the one-stop-shop for all publishing needs, from origination to launch, measuring successes and failures to improve products and programs, including: events, video, competitive play, and much more
                                    Foster strong relationships with partners and senior leaders; XP with negotiations and influential communication skills will net you bonus points
                                    Put your problem-solving, strategic and analytical skills to use, taking advantage of your skills and our available data to drive strategy and business action
                                    Increase player satisfaction, knowing that the true “win” within your role means players freaking love what you’ve done, and other Riot regions adopt and implement your idea",
            "job_location": "Dublin, Ireland"
        }
    

### Add a Job [POST]
+ Request (application/json)

+ Response 201 (application/json)

    + Header
    
            Location: /models/Job.py/2
    
    + Body
    
            {
                "company_id": 1,
                "company_name": "Riot Games",
                "job_id": 1
                "job_position": Game Developer,
                "job_description": "",
                "job_expectations": ""
                "job_responsibilities": ""
                "job_location": "",
            }
