FORMAT: 1A

# Banana-Fish
BananaFish is an API allowing people to find games, companies, and jobs.

# Group Game
API calls related resources of the **Games API**

## Games [/notes]
### Get a game [GET]
+ Response 200 (application/json)

        [{
          "game_id": 1, "name": "League of Legends", image: "image.jpg", 
           original_release_date: "01-23-2015", deck: "sdfds", description: "Game description",
           company_id: 1
        }, {
          "game_id": 2, "name": "League of Legends", image: "image.jpg", 
           original_release_date: "01-23-2015", deck: "sdfds", description: "Game description",
           company_id: 1
        }]

### Create a Game [POST]
+ Request (application/json)

        { "title": "League of Legends" }

+ Response 201 (application/json)

        { "id": 3, "title": "League of Legends" }

## Note [/games/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204